---
title: "Alternate Gold Standard"
author: "Robert Allaway (Sage Bionetworks), Adrià Fernandez-Torras (SBNB)"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    code_fold: hide
    toc: true
    toc_float: true
---

## Introduction

## Setup

```{r echo=TRUE, message=FALSE, warning=FALSE}
library(dplyr)
library(magrittr)
library(readr)
library(tidyr)
library(purrr)
library(ggplot2)
library(synapser)
library(forcats)
synLogin()

set.seed(27651030)

query <- synTableQuery("SELECT * FROM syn22316156 where status = \'ACCEPTED\'")$filepath %>% 
  read_csv() %>% 
  filter(ROW_ID != 9696740, !is.na(writeUp))

query <- query %>% 
  arrange(desc(sc1_score)) %>% 
  mutate(rank = 1:nrow(.)) 

prediction_paths <- sapply(query$prediction_fileid, function(x){
  synGet(x)$path
})

get_user_or_team_names <- function(id){
 name <- try(synGetTeam(as.integer(id))$name, silent = T) ##try to get the team name from id 
 if(class(name)=='try-error'){ ##if it is not a team, will return error, so then try to get user profile
 try({
   prof <- synGetUserProfile(id = id) ##get first and last name
   fn <- prof$firstName
   ln <- prof$lastName
   if(is.null(fn) | is.null(ln)){
     un <- prof$userName
     return(un) 
   }else if(fn == "" | ln == ""){ ##if empty, get username instead
     un <- prof$userName
     return(un)
   }else{
     return(paste(fn, ln))
   }
   })
   }else{
     return(name)
   }
}

query <- mutate(query, participant_name = sapply(submitterid, get_user_or_team_names)) %>% 
      mutate(participant_name = case_when(participant_name == "Hyunmin Kim" ~ "Theragen", 
                                participant_name != "Hyunmin Kim" ~ participant_name)) 

prediction_paths <- setNames(prediction_paths, query$participant_name)

frac_overlap <- function(gold, pred){
  sum(gold %in% pred)/length(gold)
}

# gold_path <- synGet("syn21302164")$path
template_path <- synGet('syn21321426')$path

null_sc1_path <- synGet('syn21362374')$path
null_sc2_path <- synGet('syn21362377')$path

```

Define the scoring functions. THe other three (DTC, drugbank, and chembl) require a different scoring function to account for the different universe. They also require a different null model. This means that the magnitudes of the scores will not really be comparable, but we can likely compare the ranks of the teams in each scoring scenario. 

```{r echo=TRUE, message=FALSE, warning=FALSE}

frac_overlap <- function(gold, pred){
  sum(gold %in% pred)/length(gold)
}


score_dream <- function(prediction_path,
                  gold_path,
                  null_model_path_sc1, 
                  null_model_path_sc2){
  
  #most obnoxiously long vector of targets here
  
  targs <- c("EGFR","CSNK2A2","BMP2K","AAK1","Q6ZSR9","GAK","PRKD2","PRKD3","SIK2","SIK3","PLK4","AURKA","AURKB","PTK2",
    "FER","PTK2B","TNK1","TNK2","MAP2K5","MAP2K1","MAP2K2","PDGFRB","STK10","SLK","MAP4K2","MAP4K5","MAP4K3",
    "MET","CDK2","CDK5","CDK16","CDK9","GSK3A","GSK3B","CDK7","ERCC2","CDK1","CDK12","CDK13","CLK1","DYRK1A",
    "CDK17","CDK4","CDK6","FGFR1","MAPK10","MAPK8","MAPK9","ADCK1","STK16","NEK9","FECH","CSNK1A1","CSNK1E",
    "CSNK1D","MAP3K4","WEE1","MST1R","PIP4K2C","IRAK1","TAOK3","PIM1","TAOK1","CIT","PRKX","PRKY","CDC42BPA",
    "CDC42BPB","PRKACA","PRKACB","PRKCQ","CLK4","PAK6","PRKACG","RPS6KB1","MAPK7","PRKG1","PRKCI","CDKL5","CDK18",
    "ADRBK1","STK11","EPHB3","BRAF","NLK","TGFBR2","CSK","MYLK","FGR","TESK1","KIT","ULK1","FES","IGF1R","INSR",
    "JAK2","STK26","CAMK4","TAOK2","EIF2AK1","ICK","CSNK1G2","CSNK1G1","CSNK1G3","CLK2","TP53RK","MINK1","MAPK15",
    "ERN1","MAP2K6","MAP3K5","MAP3K6","MAP2K3","ERN2","MAPK1","MAPK3","AKT3","AKT1","AKT2","RPS6KA5","ACVRL1",
    "MAPKAPK5","NEK1","ARAF","ACAD10","ADCK3","ACVR2B","PAK2","CLK3","MAPKAPK3","PLK1","PDXK","DCK","ADK","PKMYT1",
    "NUAK2","HSP90AB2P","STK24","CMPK1","GARS","ACOX3","ACAD11","DCTPP1","NEK7","SMC2","TOP2B","MYH10","PIM2",
    "CAMK1G","PIP4K2A","PIP4K2B","AK2","NME2","CDC42BPG","AP1G1","DHCR24","SLC25A5","ACTR3","SNRNP200",
    "CARS","DNAJA1","PFKP","MAT2A","IPO7","STK38L","AIMP1","CDC7","PRKAR2A","EPHA1","EPHA7","BMPR1B","BMPR1A",
    "TYK2","BMPR2","MAP3K2","MAP3K3","SYK","NEK3","BUB1","LATS1","MAP3K11","IKBKE","TBK1","STK4","STK3","CDK3",
    "MARK4","MELK","IRAK4","RPS6KA4","RPS6KA1","RPS6KA3","MARK2","MARK3","RPS6KA6","PRKAG2","PRKAA1","PRKAG1","PAK4",
    "CHEK1","NTRK1","CAMK2D","CAMK2G","CAMKK2","PHKG2","MAP4K4","TNIK","MYLK3","MAP4K1","JAK1","ULK3","PRKCD",
    "PRKCA","PRKCB","PKN1","PKN2","ROCK2","ROCK1","NQO2","ACVR1","IRAK3","FLT3","RET","DDR1","DDR2","ABL2","BCR",
    "ABL1","RIPK2","MAPKAPK2","MAPK11","MAPK14","ZAK","RIPK3","YES1","LCK","SRC","FYN","HCK","LYN","FRK","EPHA2",
    "EPHA5","EPHB2","EPHB4","EPHA4","BTK","TEC","MAP3K1","LIMK1","LIMK2","PTK6","EPHB6","ACVR1B","TGFBR1")
  
  random_sample <- expr(length(null_model)) ##to be evaluated later
  
  gold <- suppressMessages(read_csv(gold_path)) %>% filter(target %in% targs)
  pred <- suppressMessages(read_csv(prediction_path)) %>% filter(target %in% targs)
  
  ###SC1 
  
  null_model <- read_rds(null_model_path_sc1)
  null_model <- sample(null_model, eval(random_sample))
  
  gold_df <- gold %>% 
    select(-cmpd) %>% 
    group_by(cmpd_id) %>% 
    nest() %>% 
    arrange(cmpd_id)
  
  pred_df <- pred %>% 
    gather(cmpd_id, confidence ,-target) %>% 
    group_by(cmpd_id) %>% 
    arrange(-confidence, target) %>% 
    slice(1:10) %>%  ##instead of top n. We eliminate ties alphabetically!
    nest() %>% 
    arrange(cmpd_id)
  
  sc1_vals <- sapply(null_model, function(x){
    
    join <- inner_join(gold_df, pred_df, by = 'cmpd_id', suffix = c("_gold", "_pred")) %>% 
      inner_join(x, by = 'cmpd_id') %>% 
      mutate(gold_pred = map2(data_gold, data_pred, function(x,y){
        frac_overlap(x$target, y$target)
      })) %>% 
      mutate(gold_null = map2(data_gold, data, function(x,y){
        frac_overlap(x$target, y$target_random)
      })) %>% 
      select(cmpd_id, gold_pred, gold_null) %>% 
      unnest(c(gold_pred, gold_null)) %>% 
      ungroup() %>% 
      summarize(pval = suppressWarnings(wilcox.test(x = gold_pred, y= gold_null, paired = T, exact = NULL)$p.value)) %>% 
      purrr::pluck('pval')
  

  if(is.nan(join)){
    join <- 1
  }
  join
  
  })
  
  sc1 <- mean(-log2(sc1_vals)) %>% signif(5)

  ##SC2
  
  null_model <- read_rds(null_model_path_sc2) 
  null_model <- sample(null_model, eval(random_sample))  
  
  pred_sc2 <- pred %>% 
    gather(cmpd_id, confidence ,-target) %>% 
    group_by(cmpd_id) %>% 
    arrange(-confidence, target) %>% 
    nest() %>% 
    arrange(cmpd_id)
  
  gold_sc2 <- gold %>% 
    select(-cmpd) %>% 
    group_by(cmpd_id) %>% 
    nest() %>% 
    arrange(cmpd_id) 
  
  sc2_vals <- sapply(null_model, function(x){
    
    join <- inner_join(gold_sc2, pred_sc2, by = 'cmpd_id', suffix = c("_gold", "_pred")) %>% 
      inner_join(x, by = 'cmpd_id') %>% 
      mutate(gold_pred = map2(data_gold, data_pred, function(x,y){
        match(x$target, y$target) %>% unique()
      })) %>% 
      mutate(gold_null = map2(data_gold, data, function(x,y){
        match(x$target, y$target_random) %>% unique()
      })) %>% 
      select(cmpd_id, gold_pred, gold_null) %>% 
      unnest(c(gold_pred, gold_null)) %>% 
      ungroup() %>% 
      summarize(pval = suppressWarnings(wilcox.test(x = gold_pred, y= gold_null, paired = T, exact = NULL)$p.value)) %>% 
      purrr::pluck('pval')
    
    if(is.nan(join)){
      join <- 1
    }
    join
    
  })
  
  sc2 <- mean(-log2(sc2_vals)) %>% signif(5)
  
  score <- c("sc1" = sc1, 
             "sc2" = sc2)
  
  return(score)
}

score_others <- function(prediction_path,
                  gold_path,
                  null_model_path_sc1, 
                  null_model_path_sc2){
  
  random_sample <- expr(length(null_model)) ##to be evaluated later
  
  gold <- suppressMessages(read_csv(gold_path))
  pred <- suppressMessages(read_csv(prediction_path))
  
  targs <- gold$target %>% unique
  
  ###SC1 
  
  null_model <- read_rds(null_model_path_sc1)
  null_model <- sample(null_model, eval(random_sample))
  
  gold_df <- gold %>% 
    select(-cmpd) %>% 
    group_by(cmpd_id) %>% 
    nest() %>% 
    arrange(cmpd_id)
  
  pred_df <- pred %>% 
    gather(cmpd_id, confidence ,-target) %>% 
    group_by(cmpd_id) %>% 
    arrange(-confidence, target) %>% 
    slice(1:10) %>%  ##instead of top n. We eliminate ties alphabetically!
    nest() %>% 
    arrange(cmpd_id)
  
  sc1_vals <- sapply(null_model, function(x){
    join <- inner_join(gold_df, pred_df, by = 'cmpd_id', suffix = c("_gold", "_pred")) %>% 
      inner_join(x, by = 'cmpd_id') %>% 
      mutate(gold_pred = map2(data_gold, data_pred, function(x,y){
        frac_overlap(x$target, y$target)
      })) %>% 
      mutate(gold_null = map2(data_gold, data, function(x,y){
        frac_overlap(x$target, y$target_random)
      })) %>% 
      select(cmpd_id, gold_pred, gold_null) %>% 
      unnest(c(gold_pred, gold_null)) %>% 
      ungroup() %>% 
      summarize(pval = suppressWarnings(wilcox.test(x = gold_pred, y= gold_null, paired = T, exact = NULL)$p.value)) %>% 
      purrr::pluck('pval')
    
    
    if(is.nan(join)){
      join <- 1
    }
    join
    
  })
  
  sc1 <- mean(-log2(sc1_vals)) %>% signif(5)
  
  ##SC2
  
  null_model <- read_rds(null_model_path_sc2) 
  null_model <- sample(null_model, eval(random_sample))  
  
  pred_sc2 <- pred %>% 
    gather(cmpd_id, confidence ,-target) %>% 
    group_by(cmpd_id) %>% 
    arrange(-confidence, target) %>% 
    nest() %>% 
    arrange(cmpd_id)
  
  gold_sc2 <- gold %>% 
    select(-cmpd) %>% 
    group_by(cmpd_id) %>% 
    nest() %>% 
    arrange(cmpd_id) 
  
  sc2_vals <- sapply(null_model, function(x){
    join <- inner_join(gold_sc2, pred_sc2, by = 'cmpd_id', suffix = c("_gold", "_pred")) %>% 
      inner_join(x, by = 'cmpd_id') %>% 
      mutate(gold_pred = map2(data_gold, data_pred, function(x,y){
        match(x$target, y$target) %>% unique()
      })) %>% 
      mutate(gold_null = map2(data_gold, data, function(x,y){
        match(x$target, y$target_random) %>% unique()
      })) %>% 
      select(cmpd_id, gold_pred, gold_null) %>% 
      unnest(c(gold_pred, gold_null)) %>% 
      ungroup() %>% 
      summarize(pval = suppressWarnings(wilcox.test(x = gold_pred, y= gold_null, paired = T, exact = NULL)$p.value)) %>% 
      purrr::pluck('pval')
    
    if(is.nan(join)){
      join <- 1
    }
    join
    
  })
  
  sc2 <- mean(-log2(sc2_vals)) %>% signif(10)
  
  score <- c("sc1" = sc1, 
             "sc2" = sc2)
  
  return(score)
}

```

```{r}
dream_gs <- synGet('syn21302164')$path
dtc_gs <- synGet('syn22332110')$path
drugbank_gs <- synGet("syn22332109")$path
chembl_gs <- synGet('syn22332111')$path

full_null_model_sc1_path <- synGet("syn22332625")$path
full_null_model_sc2_path <- synGet("syn22332629")$path

dream_scores <- sapply(prediction_paths,
       score_dream,
       gold_path = dream_gs,
       null_model_path_sc1 = null_sc1_path, 
       null_model_path_sc2 = null_sc2_path)

dtc_scores <- sapply(prediction_paths, 
       score_others,
       gold_path = dtc_gs,
       null_model_path_sc1 = full_null_model_sc1_path, 
       null_model_path_sc2 = full_null_model_sc2_path)

drugbank_scores <- sapply(prediction_paths, 
       score_others,
       gold_path = drugbank_gs,
       null_model_path_sc1 = full_null_model_sc1_path, 
       null_model_path_sc2 = full_null_model_sc2_path)

chembl_scores <- sapply(prediction_paths, 
       score_others,
       gold_path = chembl_gs,
       null_model_path_sc1 = full_null_model_sc1_path, 
       null_model_path_sc2 = full_null_model_sc2_path)

```



```{r echo=TRUE, message=FALSE, warning=FALSE}
dream_score_tidy <- t(dream_scores) %>% 
  as_tibble(rownames="team") %>% 
  rename(Kinome_sc1 = sc1, Kinome_sc2 = sc2) 

chembl_score_tidy <- t(chembl_scores) %>% 
  as_tibble(rownames="team") %>% 
  rename(ChEMBL_sc1 = sc1, ChEMBL_sc2 = sc2) 

drugbank_score_tidy <- t(drugbank_scores) %>% 
  as_tibble(rownames="team") %>% 
  rename(DrugBank_sc1 = sc1, DrugBank_sc2 = sc2) 

dtc_score_tidy <- t(dtc_scores) %>% 
  as_tibble(rownames="team") %>% 
  rename(DTC_sc1 = sc1, DTC_sc2 = sc2) 

scores <- full_join(dream_score_tidy, chembl_score_tidy) %>% 
  full_join(drugbank_score_tidy) %>% 
  full_join(dtc_score_tidy) %>% 
  gather(key = "score_type", value = "score", -team) %>% 
  mutate(score = case_when(is.infinite(score) ~ 99999,
                           !is.infinite(score) ~ score)) %>% 
  group_by(score_type) %>% 
  mutate(rank = 11-rank(score)) %>% 
  separate(score_type, into = c("gold_standard","sc"), sep = "_") %>% 
  mutate(sc = toupper(sc)) 

ord <- c("Kinome", "ChEMBL", "DTC", "DrugBank")

ggplot(scores, aes(x = fct_relevel(gold_standard, ord), y = rank, color = team)) +
  ggbeeswarm::geom_beeswarm(aes(size = -rank)) +
  geom_line(aes(group = team)) +
  facet_wrap(~sc) +
  theme_minimal() +
  scale_y_reverse("Rank", breaks = scales::pretty_breaks(10)) +
  shades::hue(scale_color_viridis_d("Team", option = "C", direction = -1), shades::scalefac(0.80)) +
  labs(x = "Gold Standard") +
  guides(size = FALSE)


ggsave("../figures/drug_activity_scores.jpg", height = 4, width = 7)
```

